<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'" />

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Http" Version="10.2.3" />
		<PackageReference Include="Asp.Versioning.Mvc" Version="10.2.1" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
		<PackageReference Include="Humanizer" Version="3.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.36" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.11" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.AnalyzerUtilities" Version="5.6.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.9.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="5.9.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Razor" Version="6.0.36" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.9.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.IdentityModel.Protocols" Version="8.22.0" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.22.0" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
		<PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="10.0.2" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
		<PackageReference Include="Mono.TextTemplating" Version="3.0.0" />
		<PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="NuGet.Protocol" Version="7.9.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="System.CodeDom" Version="10.0.11" />
		<PackageReference Include="System.Composition" Version="10.0.11" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
		<PackageReference Include="System.Reflection.MetadataLoadContext" Version="10.0.11" />
		<PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.11" />
		<PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Controllers\v1\" />
	  <Folder Include="DTOs\v1\" />
	</ItemGroup>

</Project>